# fly.toml app configuration file generated for pulse-watcher on 2024-03-24T21:14:30-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pulse-watcher'
primary_region = 'sjc'

[build]
  [build.args]
    GO_VERSION = '1.22.1'

[env]
  PORT = '8080'
  CH_ADDR = 'clickhouse-pulse.internal:9000'
  PROM_PORT = '9091'

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[metrics]
port = 9091
path = "/metrics"
