# fly.toml app configuration file generated for clickhouse-pulse on 2024-03-24T20:45:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grafana-pulse'
primary_region = 'sjc'

[build]
  image = 'grafana/grafana-enterprise:main'

[env]
  GF_INSTALL_PLUGINS = 'grafana-clickhouse-datasource'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "grafana_pulse_mount"
  destination = "/var/lib/grafana"
  initial_size = "1gb"
